networks:
  imac:
    external: true

services:
  autentication-backend:
    container_name: imac-auth-backend
    image: imac-auth-backend:1.0.0
    build: .
    volumes:
      - ~/IMAC/auth/secrets:/usr/app/generated/jwk
    restart: always
    networks:
      - imac
    environment:
      PORT: 80
      SECRET_SEED: $SECRET_SEED
      CUESTECITAS_DATABASE_URL: $CUESTECITAS_DATABASE_URL
      VALLEDUPAR_DATABASE_URL: $VALLEDUPAR_DATABASE_URL
      CORE_DATABASE_URL: $CORE_DATABASE_URL
